import { MigrationInterface, QueryRunner } from 'typeorm';
import { getListInsertStatement } from '../helpers/list';

const listName = 'country';
const listItems = [
  { id: 'AFG', description: 'Afghanistan' },
  { id: 'ALA', description: 'Åland Islands' },
  { id: 'ALB', description: 'Albania' },
  { id: 'DZA', description: 'Algeria' },
  { id: 'ASM', description: 'American Samoa' },
  { id: 'AND', description: 'Andorra' },
  { id: 'AGO', description: 'Angola' },
  { id: 'AIA', description: 'Anguilla' },
  { id: 'ATA', description: 'Antarctica' },
  { id: 'ATG', description: 'Antigua and Barbuda' },
  { id: 'ARG', description: 'Argentina' },
  { id: 'ARM', description: 'Armenia' },
  { id: 'ABW', description: 'Aruba' },
  { id: 'AUS', description: 'Australia' },
  { id: 'AUT', description: 'Austria' },
  { id: 'AZE', description: 'Azerbaijan' },
  { id: 'BHS', description: 'Bahamas' },
  { id: 'BHR', description: 'Bahrain' },
  { id: 'BGD', description: 'Bangladesh' },
  { id: 'BRB', description: 'Barbados' },
  { id: 'BLR', description: 'Belarus' },
  { id: 'BEL', description: 'Belgium' },
  { id: 'BLZ', description: 'Belize' },
  { id: 'BEN', description: 'Benin' },
  { id: 'BMU', description: 'Bermuda' },
  { id: 'BTN', description: 'Bhutan' },
  { id: 'BOL', description: 'Bolivia (Plurinational State of)' },
  { id: 'BES', description: 'Bonaire, Sint Eustatius and Saba' },
  { id: 'BIH', description: 'Bosnia and Herzegovina' },
  { id: 'BWA', description: 'Botswana' },
  { id: 'BVT', description: 'Bouvet Island' },
  { id: 'BRA', description: 'Brazil' },
  { id: 'IOT', description: 'British Indian Ocean Territory' },
  { id: 'BRN', description: 'Brunei Darussalam' },
  { id: 'BGR', description: 'Bulgaria' },
  { id: 'BFA', description: 'Burkina Faso' },
  { id: 'BDI', description: 'Burundi' },
  { id: 'CPV', description: 'Cabo Verde' },
  { id: 'KHM', description: 'Cambodia' },
  { id: 'CMR', description: 'Cameroon' },
  { id: 'CAN', description: 'Canada' },
  { id: 'CYM', description: 'Cayman Islands' },
  { id: 'CAF', description: 'Central African Republic' },
  { id: 'TCD', description: 'Chad' },
  { id: 'CHL', description: 'Chile' },
  { id: 'CHN', description: 'China' },
  { id: 'CXR', description: 'Christmas Island' },
  { id: 'CCK', description: 'Cocos (Keeling) Islands' },
  { id: 'COL', description: 'Colombia' },
  { id: 'COM', description: 'Comoros' },
  { id: 'COG', description: 'Congo' },
  { id: 'COD', description: 'Congo, Democratic Republic of the' },
  { id: 'COK', description: 'Cook Islands' },
  { id: 'CRI', description: 'Costa Rica' },
  { id: 'CIV', description: "Côte d'Ivoire" },
  { id: 'HRV', description: 'Croatia' },
  { id: 'CUB', description: 'Cuba' },
  { id: 'CUW', description: 'Curaçao' },
  { id: 'CYP', description: 'Cyprus' },
  { id: 'CZE', description: 'Czechia' },
  { id: 'DNK', description: 'Denmark' },
  { id: 'DJI', description: 'Djibouti' },
  { id: 'DMA', description: 'Dominica' },
  { id: 'DOM', description: 'Dominican Republic' },
  { id: 'ECU', description: 'Ecuador' },
  { id: 'EGY', description: 'Egypt' },
  { id: 'SLV', description: 'El Salvador' },
  { id: 'GNQ', description: 'Equatorial Guinea' },
  { id: 'ERI', description: 'Eritrea' },
  { id: 'EST', description: 'Estonia' },
  { id: 'SWZ', description: 'Eswatini' },
  { id: 'ETH', description: 'Ethiopia' },
  { id: 'FLK', description: 'Falkland Islands (Malvinas)' },
  { id: 'FRO', description: 'Faroe Islands' },
  { id: 'FJI', description: 'Fiji' },
  { id: 'FIN', description: 'Finland' },
  { id: 'FRA', description: 'France' },
  { id: 'GUF', description: 'French Guiana' },
  { id: 'PYF', description: 'French Polynesia' },
  { id: 'ATF', description: 'French Southern Territories' },
  { id: 'GAB', description: 'Gabon' },
  { id: 'GMB', description: 'Gambia' },
  { id: 'GEO', description: 'Georgia' },
  { id: 'DEU', description: 'Germany' },
  { id: 'GHA', description: 'Ghana' },
  { id: 'GIB', description: 'Gibraltar' },
  { id: 'GRC', description: 'Greece' },
  { id: 'GRL', description: 'Greenland' },
  { id: 'GRD', description: 'Grenada' },
  { id: 'GLP', description: 'Guadeloupe' },
  { id: 'GUM', description: 'Guam' },
  { id: 'GTM', description: 'Guatemala' },
  { id: 'GGY', description: 'Guernsey' },
  { id: 'GIN', description: 'Guinea' },
  { id: 'GNB', description: 'Guinea-Bissau' },
  { id: 'GUY', description: 'Guyana' },
  { id: 'HTI', description: 'Haiti' },
  { id: 'HMD', description: 'Heard Island and McDonald Islands' },
  { id: 'VAT', description: 'Holy See' },
  { id: 'HND', description: 'Honduras' },
  { id: 'HKG', description: 'Hong Kong' },
  { id: 'HUN', description: 'Hungary' },
  { id: 'ISL', description: 'Iceland' },
  { id: 'IND', description: 'India' },
  { id: 'IDN', description: 'Indonesia' },
  { id: 'IRN', description: 'Iran (Islamic Republic of)' },
  { id: 'IRQ', description: 'Iraq' },
  { id: 'IRL', description: 'Ireland' },
  { id: 'IMN', description: 'Isle of Man' },
  { id: 'ISR', description: 'Israel' },
  { id: 'ITA', description: 'Italy' },
  { id: 'JAM', description: 'Jamaica' },
  { id: 'JPN', description: 'Japan' },
  { id: 'JEY', description: 'Jersey' },
  { id: 'JOR', description: 'Jordan' },
  { id: 'KAZ', description: 'Kazakhstan' },
  { id: 'KEN', description: 'Kenya' },
  { id: 'KIR', description: 'Kiribati' },
  { id: 'PRK', description: "Korea (Democratic People's Republic of)" },
  { id: 'KOR', description: 'Korea, Republic of' },
  { id: 'KWT', description: 'Kuwait' },
  { id: 'KGZ', description: 'Kyrgyzstan' },
  { id: 'LAO', description: "Lao People's Democratic Republic" },
  { id: 'LVA', description: 'Latvia' },
  { id: 'LBN', description: 'Lebanon' },
  { id: 'LSO', description: 'Lesotho' },
  { id: 'LBR', description: 'Liberia' },
  { id: 'LBY', description: 'Libya' },
  { id: 'LIE', description: 'Liechtenstein' },
  { id: 'LTU', description: 'Lithuania' },
  { id: 'LUX', description: 'Luxembourg' },
  { id: 'MAC', description: 'Macao' },
  { id: 'MDG', description: 'Madagascar' },
  { id: 'MWI', description: 'Malawi' },
  { id: 'MYS', description: 'Malaysia' },
  { id: 'MDV', description: 'Maldives' },
  { id: 'MLI', description: 'Mali' },
  { id: 'MLT', description: 'Malta' },
  { id: 'MHL', description: 'Marshall Islands' },
  { id: 'MTQ', description: 'Martinique' },
  { id: 'MRT', description: 'Mauritania' },
  { id: 'MUS', description: 'Mauritius' },
  { id: 'MYT', description: 'Mayotte' },
  { id: 'MEX', description: 'Mexico' },
  { id: 'FSM', description: 'Micronesia (Federated States of)' },
  { id: 'MDA', description: 'Moldova, Republic of' },
  { id: 'MCO', description: 'Monaco' },
  { id: 'MNG', description: 'Mongolia' },
  { id: 'MNE', description: 'Montenegro' },
  { id: 'MSR', description: 'Montserrat' },
  { id: 'MAR', description: 'Morocco' },
  { id: 'MOZ', description: 'Mozambique' },
  { id: 'MMR', description: 'Myanmar' },
  { id: 'NAM', description: 'Namibia' },
  { id: 'NRU', description: 'Nauru' },
  { id: 'NPL', description: 'Nepal' },
  { id: 'NLD', description: 'Netherlands' },
  { id: 'NCL', description: 'New Caledonia' },
  { id: 'NZL', description: 'New Zealand' },
  { id: 'NIC', description: 'Nicaragua' },
  { id: 'NER', description: 'Niger' },
  { id: 'NGA', description: 'Nigeria' },
  { id: 'NIU', description: 'Niue' },
  { id: 'NFK', description: 'Norfolk Island' },
  { id: 'MKD', description: 'North Macedonia' },
  { id: 'MNP', description: 'Northern Mariana Islands' },
  { id: 'NOR', description: 'Norway' },
  { id: 'OMN', description: 'Oman' },
  { id: 'PAK', description: 'Pakistan' },
  { id: 'PLW', description: 'Palau' },
  { id: 'PSE', description: 'Palestine, State of' },
  { id: 'PAN', description: 'Panama' },
  { id: 'PNG', description: 'Papua New Guinea' },
  { id: 'PRY', description: 'Paraguay' },
  { id: 'PER', description: 'Peru' },
  { id: 'PHL', description: 'Philippines' },
  { id: 'PCN', description: 'Pitcairn' },
  { id: 'POL', description: 'Poland' },
  { id: 'PRT', description: 'Portugal' },
  { id: 'PRI', description: 'Puerto Rico' },
  { id: 'QAT', description: 'Qatar' },
  { id: 'REU', description: 'Réunion' },
  { id: 'ROU', description: 'Romania' },
  { id: 'RUS', description: 'Russian Federation' },
  { id: 'RWA', description: 'Rwanda' },
  { id: 'BLM', description: 'Saint Barthélemy' },
  { id: 'SHN', description: 'Saint Helena, Ascension and Tristan da Cunha' },
  { id: 'KNA', description: 'Saint Kitts and Nevis' },
  { id: 'LCA', description: 'Saint Lucia' },
  { id: 'MAF', description: 'Saint Martin (French part)' },
  { id: 'SPM', description: 'Saint Pierre and Miquelon' },
  { id: 'VCT', description: 'Saint Vincent and the Grenadines' },
  { id: 'WSM', description: 'Samoa' },
  { id: 'SMR', description: 'San Marino' },
  { id: 'STP', description: 'Sao Tome and Principe' },
  { id: 'SAU', description: 'Saudi Arabia' },
  { id: 'SEN', description: 'Senegal' },
  { id: 'SRB', description: 'Serbia' },
  { id: 'SYC', description: 'Seychelles' },
  { id: 'SLE', description: 'Sierra Leone' },
  { id: 'SGP', description: 'Singapore' },
  { id: 'SXM', description: 'Sint Maarten (Dutch part)' },
  { id: 'SVK', description: 'Slovakia' },
  { id: 'SVN', description: 'Slovenia' },
  { id: 'SLB', description: 'Solomon Islands' },
  { id: 'SOM', description: 'Somalia' },
  { id: 'ZAF', description: 'South Africa' },
  { id: 'SGS', description: 'South Georgia and the South Sandwich Islands' },
  { id: 'SSD', description: 'South Sudan' },
  { id: 'ESP', description: 'Spain' },
  { id: 'LKA', description: 'Sri Lanka' },
  { id: 'SDN', description: 'Sudan' },
  { id: 'SUR', description: 'Suriname' },
  { id: 'SJM', description: 'Svalbard and Jan Mayen' },
  { id: 'SWE', description: 'Sweden' },
  { id: 'CHE', description: 'Switzerland' },
  { id: 'SYR', description: 'Syrian Arab Republic' },
  { id: 'TWN', description: 'Taiwan, Province of China' },
  { id: 'TJK', description: 'Tajikistan' },
  { id: 'TZA', description: 'Tanzania, United Republic of' },
  { id: 'THA', description: 'Thailand' },
  { id: 'TLS', description: 'Timor-Leste' },
  { id: 'TGO', description: 'Togo' },
  { id: 'TKL', description: 'Tokelau' },
  { id: 'TON', description: 'Tonga' },
  { id: 'TTO', description: 'Trinidad and Tobago' },
  { id: 'TUN', description: 'Tunisia' },
  { id: 'TUR', description: 'Turkey' },
  { id: 'TKM', description: 'Turkmenistan' },
  { id: 'TCA', description: 'Turks and Caicos Islands' },
  { id: 'TUV', description: 'Tuvalu' },
  { id: 'UGA', description: 'Uganda' },
  { id: 'UKR', description: 'Ukraine' },
  { id: 'ARE', description: 'United Arab Emirates' },
  { id: 'GBR', description: 'United Kingdom of Great Britain and Northern Ireland' },
  { id: 'USA', description: 'United States of America' },
  { id: 'UMI', description: 'United States Minor Outlying Islands' },
  { id: 'URY', description: 'Uruguay' },
  { id: 'UZB', description: 'Uzbekistan' },
  { id: 'VUT', description: 'Vanuatu' },
  { id: 'VEN', description: 'Venezuela (Bolivarian Republic of)' },
  { id: 'VNM', description: 'Viet Nam' },
  { id: 'VGB', description: 'Virgin Islands (British)' },
  { id: 'VIR', description: 'Virgin Islands (U.S.)' },
  { id: 'WLF', description: 'Wallis and Futuna' },
  { id: 'ESH', description: 'Western Sahara' },
  { id: 'YEM', description: 'Yemen' },
  { id: 'ZMB', description: 'Zambia' },
  { id: 'ZWE', description: 'Zimbabwe' },
];

export class country1632720163646 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(getListInsertStatement(listName, listItems));
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
